"""
Plot Generation Utility Module

This module provides a utility function plot_gen() that:
1. Calls topology_gen() to generate network topology
2. Calls spatial_traffic_load_gen() to generate UE traffic data
3. Uses existing plotting logic to create and save visualizations

The module is designed to be a comprehensive plotting utility that orchestrates
the entire process from topology generation to visualization creation, making it
easy to generate network visualizations with minimal configuration.

"""

# Standard library imports
import os
import sys
import logging
from typing import Dict, List, Tuple, Any, Optional
from pathlib import Path

# Third-party imports for data manipulation and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

# Import the generation functions from sibling modules
from ..topology_gen.topology_gen import topology_gen
from ..spatial_traffic_load_gen.spatial_traffic_load_gen import (
    spatial_traffic_load_gen, 
    load_default_spatial_params, 
    load_default_time_params
)

# Optional imports for advanced plotting features
try:
    from scipy.spatial import Voronoi, voronoi_plot_2d
except ImportError:
    print("Warning: scipy.spatial.Voronoi not found. Voronoi plotting will be disabled.")
    Voronoi, voronoi_plot_2d = None, None

try:
    from shapely.geometry import Polygon
except ImportError:
    print("Error: Shapely library not found. Please install it for plotting spatial layouts: pip install Shapely")
    sys.exit(1)

# Constants for column names used throughout the module
class c:
    """Constants for column names used in DataFrames."""
    CELL_ID = "cell_id"      # Cell identifier column
    CELL_LAT = "cell_lat"    # Cell latitude column
    CELL_LON = "cell_lon"    # Cell longitude column
    LAT = "lat"              # UE latitude column
    LON = "lon"              # UE longitude column

# Configure logging for the module
logger = logging.getLogger(__name__)


class TrafficDataVisualizer:
    """
    Visualizes traffic demand data, including UE distributions, cell towers,
    and spatial area types.
    
    This class provides comprehensive visualization capabilities for network
    topology and traffic data, including:
    - Spatial area type visualization with color coding
    - Cell tower placement and Voronoi diagrams
    - UE distribution plotting with optional serving cell coloring
    - Professional plot formatting with legends and grids
    
    The visualizer is designed to work with data generated by the topology_gen
    and spatial_traffic_load_gen modules, creating publication-ready plots
    that clearly show network coverage and traffic patterns.
    """

    def __init__(self):
        """
        Initialize the TrafficDataVisualizer.
        
        This is a lightweight initialization that doesn't require any
        parameters. The visualizer is stateless and can be reused for
        multiple plot generations.
        """
        pass

    def generate_tick_visualization(self,
                                    tick_to_plot: int,
                                    ue_data_for_tick: pd.DataFrame,
                                    topology_df: pd.DataFrame,
                                    spatial_layout: List[Dict[str, Any]],
                                    spatial_params_for_colors: Dict[str, Any],
                                    plot_output_path_template: str = "./plots/ue_distribution_tick_{tick}.png",
                                    serving_cell_data_for_tick: Optional[pd.DataFrame] = None):
        """
        Generates and saves a comprehensive plot visualizing UE distribution, cell towers,
        and spatial types for a specific simulation tick.
        
        This method creates a multi-layered visualization that includes:
        1. Background spatial area polygons (colored by type)
        2. Voronoi diagram showing cell coverage areas
        3. Cell towers as black triangles
        4. UE positions as colored dots (optionally colored by serving cell)
        5. Professional legend and formatting

        Args:
            tick_to_plot (int): The simulation tick to visualize (0-based index).
            ue_data_for_tick (pd.DataFrame): DataFrame with UE data for the specified tick.
                Must contain 'lat' and 'lon' columns. If 'ue_id' is present and 
                serving_cell_data is provided, UEs will be colored by serving cell.
            topology_df (pd.DataFrame): DataFrame with network topology information.
                Must contain 'cell_lat', 'cell_lon', and 'cell_id' columns.
            spatial_layout (List[Dict[str, Any]]): List of dictionaries defining spatial cells
                from TrafficDemandModel. Each dict should contain 'bounds' (polygon 
                coordinates) and 'type' (area type name).
            spatial_params_for_colors (Dict[str, Any]): Dictionary containing "types" list
                from spatial_params.json, used to assign consistent colors to area types.
            plot_output_path_template (str): Template for the output plot file path.
                The '{tick}' placeholder will be replaced with the actual tick number.
            serving_cell_data_for_tick (Optional[pd.DataFrame]): Optional DataFrame with
                serving cell information for UEs. If provided, UEs will be colored by
                their serving cell. Must contain 'ue_id' and 'serving_cell_id' columns.
                
        Raises:
            ValueError: If required columns are missing from input DataFrames.
            
        Note:
            The method automatically creates the output directory if it doesn't exist.
            Plots are saved as PNG files with high resolution for publication quality.
        """
        logger.info(f"Generating plot for tick {tick_to_plot}...")

        # --- Extract column names with fallbacks ---
        # These constants ensure compatibility with different column naming conventions
        COL_LAT = getattr(c, 'LAT', 'lat')
        COL_LON = getattr(c, 'LON', 'lon')
        COL_CELL_LAT = getattr(c, 'CELL_LAT', 'cell_lat')
        COL_CELL_LON = getattr(c, 'CELL_LON', 'cell_lon')
        COL_CELL_ID = getattr(c, 'CELL_ID', 'cell_id')

        # --- Input validation ---
        # Check for empty or missing UE data
        if ue_data_for_tick is None or ue_data_for_tick.empty:
            logger.warning(f"No UE data provided for tick {tick_to_plot}. Skipping plot.")
            return
            
        # Validate required columns in UE data
        if not {COL_LAT, COL_LON}.issubset(ue_data_for_tick.columns):
             raise ValueError(f"UE data must include '{COL_LAT}' and '{COL_LON}' columns.")
             
        # Validate required columns in topology data
        if not {COL_CELL_LAT, COL_CELL_LON, COL_CELL_ID}.issubset(topology_df.columns):
             raise ValueError(f"Topology data must include '{COL_CELL_LAT}', '{COL_CELL_LON}', and '{COL_CELL_ID}' columns.")

        # --- Create the main plot figure ---
        # Large figure size ensures good resolution and readability
        fig, ax = plt.subplots(figsize=(14, 11))

        # --- 1. Plot Shaded Spatial Area Polygons ---
        # This section creates the background layer showing different spatial area types
        # (e.g., dense urban, suburban, rural) as colored polygons
        
        plotted_space_labels = set()  # Track which space types we've already added to legend
        spatial_legend_handles = []   # Store legend handles for spatial area types
        
        # Extract space types from parameters and create color mapping
        # This ensures consistent coloring across all plots
        space_types_defined = spatial_params_for_colors.get("types", [])
        if not space_types_defined:
            logger.warning("No 'types' defined in spatial_params_for_colors. Spatial areas may not be colored correctly.")
            # Fallback: try to get types from the layout itself, order might be inconsistent
            if spatial_layout:
                space_types_defined = sorted(list(set(cell['type'] for cell in spatial_layout)))

        # Create a color map for spatial types using matplotlib's tab10 colormap
        # This provides distinct, visually appealing colors for different area types
        cmap_spaces = plt.get_cmap('tab10', max(1, len(space_types_defined))) # Ensure at least 1 color
        space_colors = {stype: cmap_spaces(i) for i, stype in enumerate(space_types_defined)}

        # Plot each spatial area polygon
        if spatial_layout:
            logger.debug(f"Plotting {len(spatial_layout)} spatial cell areas...")
            for cell_info in spatial_layout:
                try:
                    # Create polygon from bounds coordinates
                    polygon = Polygon(cell_info["bounds"])
                    space_type = cell_info["type"]
                    
                    # Get color for this space type, default to light grey if not found
                    color = space_colors.get(space_type, 'lightgrey')
                    
                    # Fill the polygon with semi-transparent color
                    # zorder=1 ensures it appears behind other elements
                    ax.fill(*polygon.exterior.xy, color=color, alpha=0.15, zorder=1)
                    
                    # Add to legend if this space type hasn't been added yet
                    if space_type not in plotted_space_labels:
                        label_text = space_type.replace("_", " ").title()  # Convert to title case
                        spatial_legend_handles.append(Patch(facecolor=color, alpha=0.3, label=label_text))
                        plotted_space_labels.add(space_type)
                except Exception as e:
                    logger.warning(f"Could not plot spatial cell {cell_info.get('cell_id', 'N/A')}: {e}")
        else:
            logger.warning("No spatial_layout provided. Skipping background shading.")

        # --- 2. Plot Voronoi Lines (Optional) ---
        # Voronoi diagrams show the theoretical coverage areas for each cell tower
        # This helps visualize which areas are closest to each tower
        if Voronoi and voronoi_plot_2d and len(topology_df) >= 4:
            # Extract cell tower coordinates for Voronoi calculation
            points = topology_df[[COL_CELL_LON, COL_CELL_LAT]].values
            try:
                # Create Voronoi diagram from cell tower positions
                vor = Voronoi(points)
                # Plot Voronoi lines as dotted grey lines
                # zorder=2 ensures they appear above spatial areas but below towers/UEs
                voronoi_plot_2d(vor, ax=ax, show_vertices=False, line_colors="grey", 
                               lw=0.5, line_style=':', alpha=0.5, point_size=0, zorder=2)
            except Exception as e:
                logger.warning(f"Voronoi plot generation failed: {e}")
        elif len(topology_df) < 4 and Voronoi:
             logger.info("Skipping Voronoi plot: Less than 4 sites in topology.")

        # --- 3. Plot Cell Towers ---
        # Cell towers are shown as black triangles with white edges for visibility
        # zorder=10 ensures they appear on top of all other elements
        tower_handle = ax.scatter(
            topology_df[COL_CELL_LON], topology_df[COL_CELL_LAT],
            marker="^", c="black", edgecolors='white', label="Cell Towers", s=100, zorder=10
        )

        # --- 4. Plot UEs (User Equipment) ---
        # This section handles UE plotting with optional serving cell coloring
        # UEs can be colored by their serving cell or plotted in a single color
        
        ue_plot_data = ue_data_for_tick.copy()  # Work with a copy to avoid modifying original data
        ue_legend_handles = []                  # Store legend handles for UE categories
        plotted_ue_labels = set()               # Track which UE categories we've added to legend
        no_serve_handle = None                  # Handle for UEs without serving cells

        # Check if we have serving cell data to color UEs by their serving cell
        if serving_cell_data_for_tick is not None and not serving_cell_data_for_tick.empty:
            # Validate that serving cell data has required columns
            if not {'ue_id', 'serving_cell_id'}.issubset(serving_cell_data_for_tick.columns):
                logger.warning("serving_cell_data_for_tick missing 'ue_id' or 'serving_cell_id'. Plotting all UEs with default color.")
                # Fallback: plot all UEs in blue
                ax.scatter(ue_plot_data[COL_LON], ue_plot_data[COL_LAT], color='blue', alpha=0.6, s=15, zorder=5, label="UEs")
                ue_legend_handles.append(plt.Line2D([0], [0], marker='o', color='blue', linestyle='', ms=5, label="UEs"))
            else:
                # Ensure 'ue_id' is in ue_plot_data for merging
                if 'ue_id' not in ue_plot_data.columns:
                    logger.warning("'ue_id' column missing in ue_data_for_tick. Cannot merge serving cell data. Plotting with default color.")
                    # Fallback: plot all UEs in blue
                    ax.scatter(ue_plot_data[COL_LON], ue_plot_data[COL_LAT], color='blue', alpha=0.6, s=15, zorder=5, label="UEs")
                    ue_legend_handles.append(plt.Line2D([0], [0], marker='o', color='blue', linestyle='', ms=5, label="UEs"))
                else:
                    # Merge UE data with serving cell information
                    ue_plot_data = pd.merge(ue_plot_data, serving_cell_data_for_tick[['ue_id', 'serving_cell_id']], on="ue_id", how="left")
                    
                    # Get unique serving cells and create color mapping
                    unique_serving_cells = sorted(ue_plot_data["serving_cell_id"].dropna().unique())
                    cmap_ues = plt.get_cmap("viridis", max(1, len(unique_serving_cells)))

                    # Plot UEs for each serving cell with different colors
                    for i, cell_id_val in enumerate(unique_serving_cells):
                        cell_ues = ue_plot_data[ue_plot_data["serving_cell_id"] == cell_id_val]
                        if not cell_ues.empty:
                            # Normalize color index to avoid edge cases
                            color = cmap_ues(i / max(1, len(unique_serving_cells) -1e-9))
                            ax.scatter(cell_ues[COL_LON], cell_ues[COL_LAT], color=color, alpha=0.7, s=10, zorder=5)
                            
                            # Add to legend
                            label = f"UEs ({cell_id_val})"
                            if label not in plotted_ue_labels:
                                ue_legend_handles.append(plt.Line2D([0], [0], marker='o', color=color, linestyle='', ms=5, label=label))
                                plotted_ue_labels.add(label)
                    
                    # Plot UEs without serving cells in red with X markers
                    ues_no_serve = ue_plot_data[ue_plot_data["serving_cell_id"].isna()]
                    if not ues_no_serve.empty:
                        ax.scatter(ues_no_serve[COL_LON], ues_no_serve[COL_LAT], c='red', marker='x', s=15, label="UEs (No Serving)", zorder=6)
                        no_serve_handle = plt.Line2D([0],[0], marker='x', color='red', linestyle='', ms=6, label="UEs (No Serving)")
        else: 
            # No serving cell data available, plot all UEs in a single color
            ax.scatter(ue_plot_data[COL_LON], ue_plot_data[COL_LAT], color='blue', alpha=0.6, s=15, zorder=5, label="UEs")
            ue_legend_handles.append(plt.Line2D([0], [0], marker='o', color='blue', linestyle='', ms=5, label="UEs"))

        # --- 5. Setup Plot Appearance & Combined Legend ---
        # Configure plot labels and title for clarity
        ax.set_xlabel("Longitude")
        ax.set_ylabel("Latitude")
        ax.set_title(f"UE Distribution, Serving Cells, and Spatial Types (Tick {tick_to_plot})")

        # Combine all legend handles from different plot elements
        all_handles = [tower_handle] + spatial_legend_handles + ue_legend_handles
        if no_serve_handle:
            all_handles.append(no_serve_handle)
        
        # Create comprehensive legend positioned to the right of the plot
        if all_handles:
            ax.legend(handles=all_handles, loc='center left', bbox_to_anchor=(1.02, 0.5), 
                     fontsize='small', title="Legend", frameon=True)
        
        # Add grid for better readability
        ax.grid(True, linestyle='--', alpha=0.4)
        
        # Adjust layout to accommodate the legend
        plt.subplots_adjust(right=0.75) # Make room for the legend on the right

        # --- 6. Save Plot ---
        # Generate output filename and ensure directory exists
        output_filename = plot_output_path_template.format(tick=tick_to_plot)
        output_dir = os.path.dirname(output_filename)
        
        # Create output directory if it doesn't exist
        if output_dir: # Only create if not saving to current directory
            os.makedirs(output_dir, exist_ok=True)
        
        # Save the plot with high quality settings
        try:
            plt.savefig(output_filename, bbox_inches='tight', dpi=300)  # High DPI for quality
            logger.info(f"Plot saved: {output_filename}")
        except Exception as e:
            logger.error(f"Failed to save plot {output_filename}: {e}")
        finally:
            plt.close(fig) # Always close the figure to free memory


def plot_gen(
    *,
    output_dir: str = "./plots",
    organize_by_day: bool = False,
    num_sites: int = 5,
    cells_per_site: int = 3,
    lat_range: Tuple[float, float] = (40.7, 40.8),
    lon_range: Tuple[float, float] = (-74.05, -73.95),
    default_cell_tilt: float = 12.0,
    days: int = 2,
    spatial_params: Optional[Dict[str, Any]] = None,
    time_params: Optional[Dict[str, Any]] = None,
    num_ues: int = 300,
    rng_seed: Optional[int] = 0,
    plot_max_ticks: int = 0,  # 0 means plot all ticks
    generate_dummy_training: bool = True,
    num_training_samples: int = 6000,
    training_ticks: int = 24,
) -> Dict[str, Any]:
    """
    Main utility function that orchestrates the entire plot generation process.
    
    This function serves as the primary entry point for generating network visualizations.
    It coordinates the following steps:
    1. Generate network topology using topology_gen()
    2. Generate spatial layout and traffic data using spatial_traffic_load_gen()
    3. Create visualizations for each day and tick using TrafficDataVisualizer
    4. Save plots in an organized directory structure
    
    The function is designed to be flexible and configurable, allowing users to
    customize the network topology, traffic patterns, and visualization parameters
    to suit their specific needs.
    
    Args:
        output_dir (str): Directory to save generated plots. Will be created if it doesn't exist.
            Default: "./plots"
        organize_by_day (bool): Whether to organize plots into day-specific subdirectories.
            If False, all plots are saved directly to output_dir.
            If True, plots are organized as output_dir/day_X/ue_distribution_tick_Y.png
            Default: False
        num_sites (int): Number of cell sites to generate in the network topology.
            Default: 5
        cells_per_site (int): Number of cells per site (sectors per tower).
            Default: 3
        lat_range (Tuple[float, float]): Latitude range for topology generation.
            Default: (40.7, 40.8) - roughly New York area
        lon_range (Tuple[float, float]): Longitude range for topology generation.
            Default: (-74.05, -73.95) - roughly New York area
        default_cell_tilt (float): Default cell tilt angle in degrees.
            Default: 12.0
        days (int): Number of days to simulate traffic patterns.
            Default: 2
        spatial_params (Optional[Dict[str, Any]]): Spatial parameters for traffic generation.
            If None, uses default parameters from spatial_params.json.
            Should contain 'types' and 'proportions' keys.
        time_params (Optional[Dict[str, Any]]): Time parameters for traffic generation.
            If None, uses default parameters from time_params.json.
            Should contain 'total_ticks' and 'time_weights' keys.
        num_ues (int): Number of UEs (User Equipment) per tick.
            Default: 300
        rng_seed (Optional[int]): Random seed for reproducibility.
            If None, uses system random seed. Default: 0
        plot_max_ticks (int): Maximum number of ticks to plot per day.
            If 0, plots all ticks. Useful for limiting output when testing.
            Default: 0
        generate_dummy_training (bool): Whether to generate dummy training data.
            Default: True
        num_training_samples (int): Number of training samples to generate.
            Default: 6000
        training_ticks (int): Number of training ticks for dummy data.
            Default: 24
    
    Returns:
        Dict[str, Any]: Comprehensive results dictionary containing:
            - 'topology_df': Generated topology DataFrame with cell information
            - 'config_df': Generated configuration DataFrame with cell parameters
            - 'dummy_training_df': Generated dummy training DataFrame (if requested)
            - 'ue_data_per_day': List of UE DataFrames, one per day
            - 'spatial_layout': Generated spatial layout for visualization
            - 'spatial_params': Spatial parameters used for generation
            - 'time_params': Time parameters used for generation
            - 'plots_generated': List of generated plot file paths
    
    Raises:
        ValueError: If required parameters are invalid or missing.
        ImportError: If required dependencies (shapely, scipy) are not available.
        
    Example:
        >>> from maveric_platform_modules.plot_gen import plot_gen
        >>> result = plot_gen(
        ...     output_dir="./my_plots",
        ...     num_sites=10,
        ...     days=1,
        ...     num_ues=500
        ... )
        >>> print(f"Generated {len(result['plots_generated'])} plots")
    """
    logger.info("Starting plot generation process...")
    
    # --- Setup and Validation ---
    # Create output directory and ensure it exists
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    logger.info(f"Output directory: {output_path.absolute()}")
    
    # Load default parameters if not provided by user
    # This ensures consistent behavior and reduces configuration burden
    if spatial_params is None:
        spatial_params = load_default_spatial_params()
        logger.info("Using default spatial parameters")
    
    if time_params is None:
        time_params = load_default_time_params()
        logger.info("Using default time parameters")
    
    # --- Step 1: Generate Network Topology ---
    # Create the base network infrastructure including cell sites and configuration
    logger.info("Generating topology...")
    topology_data = topology_gen(
        num_sites=num_sites,
        cells_per_site=cells_per_site,
        lat_range=lat_range,
        lon_range=lon_range,
        default_cell_tilt=default_cell_tilt,
        generate_dummy_training=generate_dummy_training,
        num_training_samples=num_training_samples,
        training_ticks=training_ticks,
        rng_seed=rng_seed,
    )
    
    # Unpack the returned data from topology generation
    topology_df, config_df, dummy_training_df = topology_data
    logger.info(f"Generated topology with {len(topology_df)} cells from {num_sites} sites")
    
    # --- Step 2: Generate Traffic Data ---
    # Create UE traffic patterns based on the generated topology
    logger.info("Generating spatial layout and traffic data...")
    ue_data_per_day = spatial_traffic_load_gen(
        topology_df=topology_df,
        days=days,
        spatial_params=spatial_params,
        time_params=time_params,
        num_ues=num_ues,
        rng_seed=rng_seed,
    )
    
    logger.info(f"Generated traffic data for {len(ue_data_per_day)} days")
    
    # --- Step 3: Generate Spatial Layout for Visualization ---
    # Create the spatial area definitions needed for background visualization
    from ..spatial_traffic_load_gen.spatial_traffic_load_gen import TrafficDemandModel
    model = TrafficDemandModel()
    spatial_layout = model.generate_spatial_layout(topology_df=topology_df, spatial_params=spatial_params)
    logger.info(f"Generated spatial layout with {len(spatial_layout)} spatial cells")
    
    # --- Step 4: Generate Visualizations ---
    # Create the visualizer instance and generate plots for each day and tick
    visualizer = TrafficDataVisualizer()
    plots_generated = []
    
    logger.info("Generating plots...")
    
    # Process each day of traffic data
    for day_idx, ue_data_day in enumerate(ue_data_per_day):
        # Skip days with no data
        if ue_data_day.empty:
            logger.warning(f"No UE data for day {day_idx + 1}, skipping plots")
            continue
            
        day = day_idx + 1
        
        # Determine output directory structure based on organize_by_day parameter
        if organize_by_day:
            # Create day-specific directory for organized output
            day_plot_dir = output_path / f"day_{day}"
            day_plot_dir.mkdir(exist_ok=True)
            base_plot_dir = day_plot_dir
        else:
            # Use the main output directory for all plots
            base_plot_dir = output_path
        
        # Get all unique ticks for this day
        unique_ticks = sorted(ue_data_day['tick'].unique())
        
        # Apply tick limit if specified (useful for testing or performance)
        if plot_max_ticks > 0 and len(unique_ticks) > plot_max_ticks:
            # Sample ticks evenly across the day
            sample_indices = np.linspace(0, len(unique_ticks) - 1, plot_max_ticks, dtype=int)
            ticks_to_plot = [unique_ticks[i] for i in sample_indices]
        else:
            ticks_to_plot = unique_ticks
        
        logger.info(f"Generating {len(ticks_to_plot)} plots for day {day}")
        
        # Generate a plot for each selected tick
        for tick in ticks_to_plot:
            # Extract UE data for this specific tick
            ue_data_for_tick = ue_data_day[ue_data_day['tick'] == tick].copy()
            
            # Skip ticks with no data
            if ue_data_for_tick.empty:
                logger.warning(f"No UE data for day {day}, tick {tick}, skipping")
                continue
            
            # Define output path for this plot
            if organize_by_day:
                # Simple filename when organizing by day (day info is in directory)
                plot_path_template = str(base_plot_dir / "ue_distribution_tick_{tick}.png")
            else:
                # Include day in filename when not organizing by day
                # Create filename with day info but only use {tick} placeholder for visualization method
                filename = f"ue_distribution_day{day}_tick_{tick}.png"
                plot_path_template = str(base_plot_dir / filename)
            
            # Generate the visualization
            try:
                visualizer.generate_tick_visualization(
                    tick_to_plot=tick,
                    ue_data_for_tick=ue_data_for_tick,
                    topology_df=topology_df,
                    spatial_layout=spatial_layout,
                    spatial_params_for_colors=spatial_params,
                    plot_output_path_template=plot_path_template
                )
                # Track successfully generated plots
                plots_generated.append(plot_path_template)
            except Exception as e:
                logger.error(f"Failed to generate plot for day {day}, tick {tick}: {e}")
    
    logger.info(f"Plot generation complete. Generated {len(plots_generated)} plots")
    
    # --- Return Comprehensive Results ---
    # Package all generated data and metadata for the caller
    return {
        'topology_df': topology_df,           # Network topology data
        'config_df': config_df,               # Cell configuration data
        'dummy_training_df': dummy_training_df, # Training data (if generated)
        'ue_data_per_day': ue_data_per_day,   # Traffic data by day
        'spatial_layout': spatial_layout,     # Spatial area definitions
        'spatial_params': spatial_params,     # Parameters used for spatial generation
        'time_params': time_params,           # Parameters used for time generation
        'plots_generated': plots_generated    # List of generated plot file paths
    }


if __name__ == '__main__':
    """
    Example usage of the plot_gen() function.
    
    This section demonstrates how to use the plot generation utility with
    custom parameters. It's designed to be run as a standalone script for
    testing and demonstration purposes.
    """
    # Configure logging for the example
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    logger.info("Running plot_gen() example...")
    
    # Run the plot generation with example parameters
    # These parameters create a small, manageable example for demonstration
    result = plot_gen(
        output_dir="./example_plots",  # Save plots to example_plots directory
        organize_by_day=False,         # Save all plots to same directory (default)
        num_sites=3,                   # Small network with 3 sites
        cells_per_site=2,              # 2 cells per site (6 total cells)
        days=1,                        # Single day simulation
        num_ues=100,                   # 100 UEs per tick
        plot_max_ticks=5,              # Limit to 5 plots for quick example
        rng_seed=42                    # Fixed seed for reproducible results
    )
    
    # Display results summary
    logger.info(f"Generated {len(result['plots_generated'])} plots")
    logger.info(f"Plots saved to: {result['plots_generated']}")
    logger.info("Example complete!")
